---
# tasks file for joining_worker
- name: TCP port 6443 on master is reachable from worker
  wait_for: "host={{ hostvars['control1']['ansible_default_ipv4']['address'] }} port=6443 timeout=1"

- name: join cluster
  shell: "{{ hostvars['control1'].join_command }} --ignore-preflight-errors=all >> node_joined.log"
  args:
    chdir: /home/ubuntu
    creates: node_joined.log
